NookMainSolution/NookMainApp/Models/Rentee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NookMainApp.Models
{
    public class Rentee : UserInfo
    {
        public Rentee()
        {
            this.Interests = new HashSet<Interest>();
        }

        public virtual ICollection<Interest> Interests { get; set; }
       
        [Display(Name = "Hourly Fee (SG$)")]
        public double Fee { get; set; }
    }
}

NookMainSolution/NookMainApp/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NookMainApp.Models;
using NookMainApp.Services;
using NookMainApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NookMainApp.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ISingleUserRepo<string, Appointment> _srepo;
        private readonly IRepo<int, Appointment> _repo;
        private readonly IRepo<string, Rentee> _rrepo;
        private readonly IRepo<string, Renter> _r_repo;

        IHttpContextAccessor HttpContextAccessor;

        public AppointmentController(ISingleUserRepo<string, Appointment> srepo, IRepo<int, Appointment> repo, 
            IRepo<string, Rentee> rrepo, IRepo<string, Renter> r_repo)
        {
            _srepo = srepo;
            _repo = repo;
            _rrepo = rrepo;
            _r_repo = r_repo;
        }

        // GET: AppointmentController
        public async Task<ActionResult> AllAppointment()
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _srepo.GetToken(token);

                var userName = HttpContext.Session.GetString("username");
                var appointments = await _srepo.GetAll(userName);
                return View(appointments);
            }

            return RedirectToAction("SessionExpired", "Home");
        }

        // GET: AppointmentController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);
                _rrepo.GetToken(token);

                var appt = await _repo.Get(id);
                var rentee = await _rrepo.Get(appt.RenteeUserName);
                if (appt != null)
                {
                    var appointment = new AppointmentViewModel
                    {
                        AppointmentId = appt.AppointmentId,
                        Fees = rentee.Fee,
                        TotalFees = appt.Fees,
                        StartDateTime = appt.StartDateTime,
                        EndDateTime = appt.EndDateTime,
                        Status = appt.Status,
                        Remark = appt.Remark,
                        Rentee = rentee,
                        RenterUserName = appt.RenterUserName
                    };

                    return View(appointment);
                }
                return View();
            }

            return RedirectToAction("SessionExpired", "Home");
        }

        public async Task<ActionResult> CreateAppointment(string UserId)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _r_repo.GetToken(token);
                _rrepo.GetToken(token);

                if (HttpContext.Session.GetString("username") != null)
                {
                    var ren = await _r_repo.Get(HttpContext.Session.GetString("username"));
                    if (ren == null)
                        return RedirectToAction("Create", "Renter");
                }

                var rentee = await _rrepo.Get(UserId);
                var appointment = new AppointmentViewModel { Rentee = rentee, Fees = rentee.Fee };

                return View(appointment);
            }

            return RedirectToAction("SessionExpired", "Home");

        }

        // POST: AppointmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAppointment(AppointmentViewModel appointment)
        {
            try
            {
                if (HttpContext.Session.GetString("token") != null)
                {
                    string token = HttpContext.Session.GetString("token");
                    _repo.GetToken(token);

                    appointment.RenterUserName = HttpContext.Session.GetString("username");

                    bool isRenterApptDuplicated = await CheckingRenterAppointment(appointment.RenterUserName, appointment.StartDateTime, appointment.EndDateTime);
                    if (!isRenterApptDuplicated)
                    {
                        ViewBag.Message = "Sorry, you already have a appointment on same day and time. Please check.";
                        return View(appointment);
                    }

                    var appt = new Appointment
                    {
                        RenteeUserName = appointment.RenteeUserName,
                        RenterUserName = appointment.RenterUserName,
                        StartDateTime = appointment.StartDateTime,
                        EndDateTime = appointment.EndDateTime,
                        Fees = appointment.TotalFees,
                        PlacementDate = DateTime.Now,
                        Remark = appointment.Remark,
                        UpdateDate = DateTime.Now,
                        Status = Constant.AppointmentStatus.Pending
                    };

                    var app = await _repo.Add(appt);
                    if (app != null)
                    {
                        return RedirectToAction("AllAppointment");
                    }

                    ViewBag.Message = "Oops, please try again.";
                    return View();
                }

                return RedirectToAction("SessionExpired", "Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Oops, something is wrong. Please try again later.";
                return View();
            }
        }

        private async Task<bool> CheckingRenteeAppointment(string renteeUserName, DateTime start, DateTime end)
        {          
            string token = HttpContext.Session.GetString("token");
            _srepo.GetToken(token);

            //check rentee availability
            var appts = await _srepo.GetAll(renteeUserName);
            if (appts != null)
            {
                var upcomingAppointments = appts.Where(a => a.Status != Constant.AppointmentStatus.Cancel && a.StartDateTime > DateTime.Now).ToList();
                var crashAppointment = upcomingAppointments.Where(a => (a.StartDateTime < end && a.EndDateTime > start));

                if (crashAppointment.Any())
                {
                    return false;
                }
            }
            return true;
        }

        private async Task<bool> CheckingRenterAppointment(string userName, DateTime start, DateTime end)
        {
            string token = HttpContext.Session.GetString("token");
            _srepo.GetToken(token);

            //check if user with any same datetime appointment
            var appts = await _srepo.GetAll(userName);
            if (appts != null)
            {
                var upcomingAppointments = appts.Where(a => a.Status != Constant.AppointmentStatus.Cancel && a.StartDateTime > DateTime.Now).ToList();
                var crashAppointment = upcomingAppointments.Where(a => (a.StartDateTime < end && a.EndDateTime > start));

                if (crashAppointment.Any())
                {
                    return false;
                }
            }
            return true;
        }

        // GET: AppointmentController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);
                _rrepo.GetToken(token);

                var appt = await _repo.Get(id);
                var rentee = await _rrepo.Get(appt.RenteeUserName);
                if (appt != null)
                {
                    var appointment = new AppointmentViewModel
                    {
                        AppointmentId = appt.AppointmentId,
                        Fees = rentee.Fee,
                        TotalFees = appt.Fees,
                        StartDateTime = appt.StartDateTime,
                        EndDateTime = appt.EndDateTime,
                        Status = appt.Status,
                        Rentee = rentee,
                        Remark = appt.Remark,
                        PlacementDate = appt.PlacementDate,
                        UpdateDate = appt.UpdateDate,
                        RenterUserName = appt.RenterUserName
                    };

                    return View(appointment);
                }
                return View();
            }

            return RedirectToAction("SessionExpired", "Home");
        }

        // POST: AppointmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AppointmentViewModel appt)
        {
            try
            {
                if (HttpContext.Session.GetString("token") != null)
                {
                    string token = HttpContext.Session.GetString("token");
                    _repo.GetToken(token);

                    var newAppt = appt;
                    var appointment = await _repo.Get(appt.AppointmentId);
                    if (appointment != null)
                    {
                        bool isRenterApptDuplicated = await CheckingRenterAppointmentByApptId(appointment, newAppt);
                        if (!isRenterApptDuplicated)
                        {
                            ViewBag.Message = "Sorry, you already have a appointment on same day and time. Please check.";
                            return View(newAppt);
                        }

                        var latestAppt = new Appointment
                        {

NookMainSolution/NookMainApp/Controllers/RenteeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NookMainApp.Models;
using NookMainApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NookMainApp.Controllers
{
    public class RenteeController : Controller
    {
        private readonly IRepo<string, Rentee> _repo;

        public RenteeController(IRepo<string, Rentee> repo)
        {
            _repo = repo;
        }

        IEnumerable<SelectListItem> GetGender()
        {
            List<SelectListItem> cats = new List<SelectListItem>();
            cats.Add(new SelectListItem { Text = "Female", Value = "Female" });
            cats.Add(new SelectListItem { Text = "Male", Value = "Male" });
            return cats;
        }

        // GET: RenteeController
        public async Task<ActionResult> IndexAsync()
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");

                _repo.GetToken(token);
                var rens = await _repo.GetAll();
                return View(rens.ToList());
            }

            return RedirectToAction("SessionExpired", "Home");
        }

        // GET: RenteeController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);

                ViewBag.username = HttpContext.Session.GetString("username");
                id = HttpContext.Session.GetString("username");
                var ren = await _repo.Get(id);
                return View(ren);
            }

            return RedirectToAction("SessionExpired", "Home");

        }

        // GET: RenteeController/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                ViewBag.Genders = GetGender();
                return View();
            }
            return RedirectToAction("SessionExpired", "Home");
        }

        // POST: RenteeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Rentee ren)
        {
            try
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);

                ViewBag.Genders = GetGender();
                ren.UserId = HttpContext.Session.GetString("username");
                if(ren.Image == null)
                {
                    switch (ren.Gender)
                    {
                        case "Female": ren.Image = "https://restorixhealth.com/wp-content/uploads/2018/08/No-Image.png"; break;
                        case "Male": ren.Image = "https://restorixhealth.com/wp-content/uploads/2018/08/No-Image.png"; break;
                        default: ren.Image = "https://t3.ftcdn.net/jpg/04/34/72/82/360_F_434728286_OWQQvAFoXZLdGHlObozsolNeuSxhpr84.jpg"; break;
                    }
                }
                await _repo.Add(ren);
                return RedirectToAction("Details");
            }
            catch
            {
                return View();
            }
        }

        // GET: RenteeController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);
                id = HttpContext.Session.GetString("username");

                ViewBag.Genders = GetGender();
                var ren = await _repo.Get(id);
                return View(ren);
            }

            return RedirectToAction("SessionExpired", "Home");
        }

        // POST: RenteeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Rentee ren)
        {
            try
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);

                ViewBag.Genders = GetGender();

                var app = await _repo.Update(ren);
                if (app != null)
                {
                    ViewBag.Message = "Details updated";
                    return RedirectToAction("Details");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: RenteeController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);

                var ren = await _repo.Get(id);
                return View(ren);
            }

            return RedirectToAction("SessionExpired", "Home");

        }

        // POST: RenteeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, Rentee ren)
        {
            try
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);
                id = HttpContext.Session.GetString("username");

                await _repo.Delete(id);
                return RedirectToAction("myDash", "User");
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> GetAllRentees()
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);

                ViewBag.LoginUser = HttpContext.Session.GetString("username");
                var rentees = await _repo.GetAll();
                return View(rentees);
            }

            return RedirectToAction("SessionExpired", "Home");

        }

        public async Task<ActionResult> GetRenteeDetails(string id)
        {
            if (HttpContext.Session.GetString("token") != null)
            {
                string token = HttpContext.Session.GetString("token");
                _repo.GetToken(token);

                ViewBag.LoginUser = HttpContext.Session.GetString("username");
                var ren = await _repo.Get(id);
                return View(ren);
            }

            return RedirectToAction("SessionExpired", "Home");

        }
    }
}

NookMainSolution/NookMainApp/Views/Rentee/Create.cshtml
@model NookMainApp.Models.Rentee

@{
    ViewData["Title"] = "Add Info";
}

<h2>Add your details!</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @*<div class="form-group">
            <label asp-for="UserId" class="control-label"></label>
            <input asp-for="UserId" class="form-control" />
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" onchange="birthdateValidate()" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
                <span id="alertMessage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" asp-items="ViewBag.Genders" class="form-control">
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <input asp-for="About" class="form-control" />
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            @*<div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
            </label>
        </div>*@
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-info" />
            @*<a asp-action="Index" class="btn btn-outline-info">Back to List</a>*@
        </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>

    const birthdate = document.getElementById("DOB").value;

    function birthdateValidate() {
        var currentBirthdate = document.getElementById("DOB").value;

        //get today date
        var currentDate = new Date().toISOString();

        // calculate age comparing currentBirthdate and birthday
        var difference = (new Date(currentDate) - new Date(currentBirthdate));
        var myAge = difference / 31557600000;
        if (myAge < 18) {
            document.getElementById("alertMessage").innerHTML = "User must be at least 18 years old";
            document.getElementById("DOB").value = birthdate;
        }
        else
            document.getElementById("alertMessage").innerHTML = null;
    }

</script>

}

NookMainSolution/NookMainApp/Views/Rentee/Details.cshtml
@model NookMainApp.Models.Rentee

@{
    ViewData["Title"] = "My Details";
}

<h2>My own info..</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <img src="@Html.DisplayFor(model => model.Image)" alt="profile image" width="200" style="object-fit: cover; object-position: left;">
    </div>

    <div class="col-md-8">
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.UserId)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.UserId)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.FullName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.FullName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.NickName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NickName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.DOB)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.DOB)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.About)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.About)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Fee)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Fee)
            </dd>
            @*<dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.IsActive)
            </dd>*@
        </dl>

        <div>
            @if (Model.UserId == ViewBag.username)
            {
                <a asp-action="Edit" class="btn btn-info">Edit details</a>
            }
            <a asp-action="Index" asp-controller="Home" class="btn btn-outline-info">Back to home</a>
        </div>
    </div>
</div>

NookMainSolution/NookMainApp/Views/Rentee/Edit.cshtml
@model NookMainApp.Models.Rentee

@{
    ViewData["Title"] = "Update Info";
}

<h2>Update your info!</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <input asp-for="UserId" class="form-control" hidden readonly />
            </div>

            @*<div class="form-group">
            <label asp-for="UserId" class="control-label"></label>
            <input asp-for="UserId" class="form-control" />
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NickName" class="control-label"></label>
                <input asp-for="NickName" class="form-control" />
                <span asp-validation-for="NickName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" onchange="birthdateValidate()" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
                <span id="alertMessage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" asp-items="ViewBag.Genders" class="form-control">
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <input asp-for="About" class="form-control" />
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fee" class="control-label"></label>
                <input asp-for="Fee" class="form-control" />
                <span asp-validation-for="Fee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            @*<div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
            </label>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info" />
                <a asp-action="Details" class="btn btn-outline-info">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>

        const birthdate = document.getElementById("DOB").value;

        function birthdateValidate() {
        var currentBirthdate = document.getElementById("DOB").value;

        //get today date
        var currentDate = new Date().toISOString();

        // calculate age comparing currentBirthdate and birthday
        var difference = (new Date(currentDate) - new Date(currentBirthdate));
        var myAge = difference / 31557600000;
        if (myAge < 18) {
            document.getElementById("alertMessage").innerHTML = "User must be at least 18 years old";
        document.getElementById("DOB").value = birthdate;
        }
        else
        document.getElementById("alertMessage").innerHTML = null;
    }

</script>
}

NookMainSolution/NookMainApp/Views/Rentee/GetAllRentees.cshtml
@model IEnumerable<NookMainApp.Models.Rentee>

@{
    ViewData["Title"] = "Friend List";
}

@*<h4>@ViewBag.LoginUser</h4>*@

<h2>Meet your new friends!</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="card m-2" style="width:300px">
            <img class="card-img-top" src="@Html.DisplayFor(modelItem => item.Image)" alt="Card image" style="width:100%">
            <div class="card-body d-flex flex-column">
                <h4 class="card-title">@Html.DisplayFor(modelItem => item.NickName)</h4>
                <p class="card-text">@Html.DisplayFor(modelItem => item.About)</p>

                <p class="card-text">
                    @Html.DisplayFor(modelItem => item.Gender) |
                    @Html.DisplayFor(modelItem => item.DOB)
                </p>

                <a href="@Url.Action("GetRenteeDetails", "Rentee", new { id = item.UserId })" class="btn btn-info mt-auto">Make appointment</a>
            </div>
        </div>
    }
</div>

NookMainSolution/NookMainApp/Views/Rentee/GetRenteeDetails.cshtml
@model NookMainApp.Models.Rentee

@{
    ViewData["Title"] = "Friend Info";
}

@*<h4>@ViewBag.LoginUser</h4>*@

<h2>Some info about your friend..</h2>

<hr />

<div class="row">
    <div class="col-md-4">
        <img src="@Html.DisplayFor(model => model.Image)" alt="profile image" width="200" style="object-fit: cover; object-position: left;">
    </div>

    <div class="col-md-8">
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.NickName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.NickName)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.DOB)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.DOB)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.About)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.About)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Fee)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Fee)
            </dd>
        </dl>

            <div>
                <a href="@Url.Action("CreateAppointment", "Appointment", new { UserId = Model.UserId })" class="btn btn-info">Make appointment</a>
                <a asp-action="GetAllRentees" class="btn btn-outline-info">Back to List</a>
            </div>
    </div>
</div>